# Fragment-level translations for draw.io labels (applied longest key first).
T = {
    # leader-follower-initialization-01
    '（连接接收器）': '(connection acceptor)',
    '（leader端用来处理对应follower的处理线性类）': '(leader-side thread that serves one follower)',
    'socker 连接': 'socket connection',
    # leader-follower-initialization-02
    '发送follower的acceptedEpoch和自己的sid信息给到leader，消息的类型是': "Send acceptedEpoch and sid to the leader; type ",
    'Leader：LearnerHandler': 'Leader: LearnerHandler',
    '解析来自follower的ACK': "Parse the follower's ACK",
    '解析来自follower的': "Parse the follower's ",
    '解析': 'Parse ',
    '发送': 'send',
    '是否有过半数': 'Quorum of sids',
    '的sid来产生新的epoch': 'for a new epoch?',
    'notifyAll，': 'notifyAll:',
    '产生新的epoch': 'new epoch produced',
    '等待过半数的sid对newEpoch的ack': 'Wait for a quorum of sids to ack newEpoch',
    'leader产生新的newEpoch': 'Leader produces newEpoch',
    '根据newEpoch产生newLeaderZxid 然后给follower，消息类型为': 'Build newLeaderZxid from newEpoch; send it as ',
    '读取来自LearnerHandler的': 'Read from LearnerHandler: ',
    '来自leader的': "leader's",
    'newEpoch大于或者等于': 'newEpoch >=',
    '自己本地的accpetEpoch': 'local acceptedEpoch',
    '的大小': '?',
    '向Leader发送对newEpoch的ack，消息类型为': 'Ack newEpoch to the leader; type ',
    '根据newEpoch生成newEpochZxid': 'Generate newEpochZxid from newEpoch',
    'zab 进入': 'ZAB enters',
    'SYNCHRONIZATION状态': 'SYNCHRONIZATION state',
    '抛出异常：newEpoch小于自己可以接受的acceptEpoch': 'Throw: newEpoch < local acceptedEpoch',
    '过半数': 'Quorum',
    '的sid对': 'of sids acked',
    '新的newEpoch ack': 'newEpoch?',
    '从waitForEpochAck 返回进入数据同步方法': 'waitForEpochAck returns; call ',
    '从waitForEpochAck': 'waitForEpochAck',
    '返回进入数据同步方法': ' returns; call ',
    # leader-follower-initialization-03
    'syncWithLeader同步来自leader的数据来恢复本地数据': 'syncWithLeader: sync from the leader',
    'syncFollower：': 'syncFollower:',
    "根据follower的f_zxid和leader的l_zxid，maxCommittedLog，minCommittedLog决定数据恢复策略":
        'pick a strategy from f_zxid, l_zxid, maxCommittedLog and minCommittedLog',
    '等待来自participant过半数': 'Wait for a quorum of participants',
    '对自己leader地位的确认': 'to confirm this leader',
    '向follower发送一个diff命令': 'Send DIFF to the follower',
    '向follower发送一个trunc命令': 'Send TRUNC to the follower',
    '把leader已经提交的但是在follower中没有的proposal发送给follower': 'Send committed proposals the follower lacks',
    '这种情况下，如果需要同步到follower端的proposal不在leader的': "If the needed proposals are not in the leader's ",
    '中，那么直接使用snap方式同步，如果在使用diff方式同步': ', use SNAP; otherwise DIFF',
    '读取diff指令': 'Read DIFF command',
    '设置同步状态为diff，然后下面会议一个循环来取到leader发送来的所有proposal，每个propsal后面还会有一个commit的指令':
        'Set sync mode to DIFF, then loop to read every proposal the leader sends; each proposal is followed by a COMMIT',
    '读取trunc指令': 'Read TRUNC command',
    '删除zxid对应的log，然后重新初始化本地db': 'Truncate the log to the zxid, then reinitialize the local DB',
    '读取到snap指令': 'Read SNAP command',
    '直接从消息输出流中反序列化结果': 'Read the snapshot from the stream',
    '读取来自leader的': "Read the leader's ",
    '<span>信息</span>': '<span> message</span>',
    '发送对': 'Send an ACK for ',
    '<br>的ACK': '',
    '向follower发送': 'Send the follower the ',
    '是否过半数': 'Quorum?',
    '启动leader 引擎': 'start the leader engine',
    '（sessionTracker，事物处理链）': '(session tracker, processor chain)',
    '设置zab状态为': 'ZAB = ',
    '启动成功': 'Started?',
    '发送给': 'Send ',
    '<span>follower</span>': '<span>to the follower</span>',
    '读取到': 'Read ',
    '启动follower的服务引擎': "Start the follower's server engine",
    '设置syncMode为None': 'Set syncMode to None',
    # leader-election-02
    '通过sendNotification': 'sendNotification sends',
    '把推荐的Leader发送给别的participant': 'the proposed leader to the other participants',
    '设置ZABState = Election': 'Set ZABState = Election',
    '生成推荐Leader的proposal封装成vote': 'Wrap the proposed leader in a vote',
    '读取别的participant发送来的r_vote': 'Read r_vote sent by another participant',
    '根据选主协议判断是不是需要使用r_vote来更新本': 'Adopt r_vote if the election rules prefer it',
    '把r_vote加入到recvset中': 'Add r_vote to recvset',
    '使用voteTracker来判断本节点的proposal是不是被选举成了Leader': 'voteTracker: has our proposal won?',
    '被选举成': 'Elected',
    '结束选举过程': 'End the election',
    # standalone-server-startup-03
    '从acceptedQueue取出SocketChannel，然后创建server端的连接管理对象NIOServerCnxn':
        'take a SocketChannel from acceptedQueue and create its NIOServerCnxn',
    '负责处理NIOServerCnxn上面的所有IO事件': 'handle all NIOServerCnxn I/O events;',
    '每个事件都会包装成IOWorkRequest任务': 'each becomes an IOWorkRequest task',
    '从updateQueue中获取所有的SelectionKey然后根据不同连接的实际情况SelectionKey注册OP_READ/OP_WRITE事件':
        'drain updateQueue and re-register OP_READ/OP_WRITE for each SelectionKey',
    '把连接请求SocketChannel放入': 'put the accepted SocketChannel into',
    '处理连接上的各种IO事件，处理完成之后向updateQueue添加selectionKey重新注册感兴趣事件任务':
        'handle the I/O event, then queue its selectionKey on updateQueue for re-registration',
    # node-creation-01 / -02
    'create 中会创建请求头RequestHeader表示请求的类型，创建ReplyHeader，创建请求体':
        'create builds a RequestHeader that records the request type, a ReplyHeader, and the request body ',
    'queuePacket会创建Packet': 'queuePacket creates a Packet',
    '提交IO任务': 'submit I/O task',
    '获取读事件SelectionKey': 'gets the read-ready SelectionKey',
    '读取消息长度到ByteBuffer': 'read length into ByteBuffer',
    '从': 'From the ',
    '读取消息体到ByteBuffer': 'read body into ByteBuffer',
    'readPayload（）': 'readPayload()',
    '把ByteBuffer转化成请求消息': 'decode the ByteBuffer into a request',
    '（先转消息头，根据消息头再转换消息体）': '(header first, then body)',
    # recycler-01
    'DefaultHandle数组': 'DefaultHandle array',
    # pooled-memory
    '内存申请者': 'memory requester',
    '申请的内存量小于一个chunk的大小': 'request smaller than one chunk',
    'JVM 堆外内存': 'JVM off-heap memory',
    '申请的内存量大于': 'request larger than',
    '一个chunk的大小': 'one chunk',
    '内存大小为16的SubpagePool链表': '16-byte<br>SubpagePool list',
    '内存大小为496的SubpagePool链表': '496-byte<br>SubpagePool list',
    '内存大小512的SubpagePool链表': '512-byte<br>SubpagePool list',
    '内存大小为4096的SubpagePool链表': '4096-byte<br>SubpagePool list',
    ' 链表': ' linked list',
    '不同PoolChunkList管理的chunk对应的可用内存大小': 'Free memory range of the chunks managed by each PoolChunkList',
    # pipeline
    '读事处理方向': 'Inbound (read) direction',
    '写事件处理方向': 'Outbound (write) direction',
    'head节点': 'head node',
    '节点': ' node',
    # zero copy
    '用户缓存空间': 'user-space buffer',
    '用户空间': 'User space',
    '内核空间': 'Kernel space',
    '页缓存': 'page cache',
    'socket 缓存': 'socket buffer',
    '磁盘': 'disk',
    '网络': 'network',
    '用户内存区': 'user memory',
    '内核缓存页': 'kernel page cache',
    '共享': 'shared',
}
